### ISSUE TITLE
Add support for uv in all script plugins

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#109]
### Feature description

Add support for uv:
- https://github.com/astral-sh/uv
- https://astral.sh/blog/uv

This should work:

```yaml
id: dbtGitDockerDuckDB
namespace: blueprint

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      runner: PROCESS
      beforeCommands:
        - curl -LsSf https://astral.sh/uv/install.sh | sh
        - source $HOME/.cargo/env
        - uv venv
        - source .venv/bin/activate
        - uv pip install dbt-duckdb
      commands:
        - dbt deps
        - dbt build
```

Currently, there are some issues to using `uv` as /bin/sh is forced as an interpreter. It makes sense to create a virtual environment with `uv` by default in all Python-based plugins when PROCESS runner is used. Alternatively, if easier, we can add UV runner that will create and activate `uv venv` by default
