### ISSUE TITLE
io.kestra.plugin.scripts.python.Commands - containerImage dynamic feature not working

### ISSUE THREAD

**Issue by japerry911** [kestra-io/plugin-scripts#147]
### Expected Behavior

```yaml
...
  - id: fetch_data
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
      - export PYTHONPATH=src
      - export GCP_PROJECT_ID={{ secret('GCP_PROJECT_ID') }}
    commands:
      - python {{ inputs.fetch_command }} --uuid_str {{ inputs.uuid_str }}
    containerImage: "us-central1-docker.pkg.dev/{{ secret('GCP_PROJECT_ID') }}/kestra/kestra-woohoo-v2:latest"
...
```

The image utilizes the following container static container image in Batch Job:
`us-central1-docker.pkg.dev/{{ secret('GCP_PROJECT_ID') }}/kestra/kestra-woohoo-v2:latest` , no secret substitution.```yaml
...
  - id: fetch_data
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
      - export PYTHONPATH=src
      - export GCP_PROJECT_ID={{ secret('GCP_PROJECT_ID') }}
    commands:
      - python {{ inputs.fetch_command }} --uuid_str {{ inputs.uuid_str }}
    containerImage: "us-central1-docker.pkg.dev/{{ secret('GCP_PROJECT_ID') }}/kestra/kestra-woohoo-v2:latest"
...
```

expected container image:

`us-central1-docker.pkg.dev/my-gcp-project-id/kestra/kestra-woohoo-v2:latest`

### Actual Behaviour

The image utilizes the following container static container image in Batch Job:
`us-central1-docker.pkg.dev/{{ secret('GCP_PROJECT_ID') }}/kestra/kestra-woohoo-v2:latest` , no secret substitution.

### Steps To Reproduce

```yaml
  - id: fetch_data
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
      - export PYTHONPATH=src
      - export GCP_PROJECT_ID={{ secret('GCP_PROJECT_ID') }}
    commands:
      - python {{ inputs.fetch_command }} --uuid_str {{ inputs.uuid_str }}
    containerImage: "us-central1-docker.pkg.dev/{{ secret('GCP_PROJECT_ID') }}/kestra/kestra-woohoo-v2:latest"
    warningOnStdErr: false
    taskRunner:
      type: io.kestra.plugin.gcp.runner.GcpBatchTaskRunner	
 ....
```

### Environment Information

- Kestra Version: 0.16.0
- Plugin version: 0.16.1
- Operating System (OS / Docker / Kubernetes): Docker Compose GCP VM
- Java Version (If not docker): n/a

### Example flow

```yaml
  - id: fetch_data
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
      - export PYTHONPATH=src
      - export GCP_PROJECT_ID={{ secret('GCP_PROJECT_ID') }}
    commands:
      - python {{ inputs.fetch_command }} --uuid_str {{ inputs.uuid_str }}
    containerImage: "us-central1-docker.pkg.dev/{{ secret('GCP_PROJECT_ID') }}/kestra/kestra-woohoo-v2:latest"
    warningOnStdErr: false
    taskRunner:
      type: io.kestra.plugin.gcp.runner.GcpBatchTaskRunner	
 ....
```
