### ISSUE TITLE
`containerImage` doesn't work with `python.Commands` on 0.18

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-scripts#151]
### Expected Behavior

When executing a flow using `io.kestra.plugin.scripts.python.Commands`, and `containerImage` set to `ghcr.io/kestra-io/pydata:latest`, pandas should be included.

### Actual Behaviour

When executing the flow, it errors as it can't find `pandas`. This suggests that `containerImage` is not working as `pydata` includes `pandas`.
![Screenshot 2024-06-07 at 17 53 31](https://github.com/kestra-io/plugin-scripts/assets/34094921/ef4c98a0-80b5-4e4e-9c6c-c842a637197c)

This works if you explicitly set the task runner to docker despite being set to docker by default.

```yaml
id: gitPython
namespace: blueprint

tasks:
  - id: pythonScripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/scripts
      branch: main
    
    - id: python
      type: io.kestra.plugin.scripts.python.Commands
      warningOnStdErr: false
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/pydata:latest
      commands:
        - python etl/global_power_plant.py
```

If taskRunner needs to be set, an error should be specified / documentation updated to clear this up.

### Environment Information

- Kestra Version: 0.18 Snapshot
- Plugin version: Latest
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

This works:
```yaml
id: gitPython
namespace: blueprint

tasks:
  - id: pythonScripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/scripts
      branch: main
    
    - id: python
      type: io.kestra.plugin.scripts.python.Commands
      warningOnStdErr: false
      docker: 
        image: ghcr.io/kestra-io/pydata:latest
      commands:
        - python etl/global_power_plant.py

```

This also works:
```yaml
id: gitPython
namespace: blueprint

tasks:
  - id: pythonScripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/scripts
      branch: main
    
    - id: python
      type: io.kestra.plugin.scripts.python.Commands
      warningOnStdErr: false
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/pydata:latest
      commands:
        - python etl/global_power_plant.py
```

This causes it to error becauses `pandas` can't be found (`containerImage` used instead):
```yaml
id: gitPython
namespace: blueprint

tasks:
  - id: pythonScripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/scripts
      branch: main
    
    - id: python
      type: io.kestra.plugin.scripts.python.Commands
      warningOnStdErr: false
      containerImage: ghcr.io/kestra-io/pydata:latest
      commands:
        - python etl/global_power_plant.py
```
