### ISSUE TITLE
Blueprint #140 on serverless lambda does not run successfully

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-scripts#156]
### Expected Behavior

The blueprint should run successfully.

### Actual Behaviour

The blueprint flow fails with an error.

Stacktrace:
```
2024-06-23 22:12:55.532Provided 2 input(s).
2024-06-23 22:12:55.553Starting command with pid 210 [/bin/sh -c set -e
sls deploy
sls invoke -f etl --log]
2024-06-23 22:12:55.561/bin/sh: 2: sls: not found
2024-06-23 22:12:55.567Command failed with code 127
2024-06-23 22:12:55.567io.kestra.core.models.tasks.runners.TaskException: Command failed with code 127
	at io.kestra.plugin.core.runner.Process.run(Process.java:118)
	at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:159)
	at io.kestra.plugin.scripts.node.Commands.run(Commands.java:90)
	at io.kestra.plugin.scripts.node.Commands.run(Commands.java:18)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)
```

### Steps To Reproduce

Put the blueprint flow in the Kestra env, and Execute the flow.

### Environment Information

- Kestra Version: 0.17.4
- Plugin version: 0.17.4
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```yaml
id: lambda
namespace: company.team

tasks:
  - id: sls_commands
    type: io.kestra.plugin.scripts.node.Commands
    description: npm install -g serverless
    runner: PROCESS
    warningOnStdErr: false
    inputFiles:
      serverless.yml: |
        service: lambda
        frameworkVersion: '3'

        provider:
          name: aws
          runtime: python3.9
          region: eu-central-1
          memorySize: 512 # optional, in MB, default is 1024; can be 128, 256, 512, 1024, 2048, 4096, 5120, ...
          timeout: 10 # optional, in seconds, default is 6

        functions:
          etl:
            handler: handler.run

      handler.py: |
        import platform
        import sys

        def extract() -> int:
            print("Extracting data...")
            return 21


        def transform(x: int) -> int:
            print("Transforming data...")
            return x * 2


        def load(x: int) -> None:
            print(f"Loading {x} into destination...")


        def run(event=None, context=None):
            raw_data = extract()
            transformed = transform(raw_data)
            load(transformed)
            print("Hello from Kestra 🚀")
            print(f"Host's network name = {platform.node()}")
            print(f"Python version = {platform.python_version()}")
            print(f"Platform information (instance type) = {platform.platform()}")
            print(f"OS/Arch = {sys.platform}/{platform.machine()}")
    commands:
      - sls deploy 
      - sls invoke -f etl --log
      # - sls remove
```

**Comment by rishi-jat** [comment]
Hi! 👋 I’d love to work on this issue Could you please assign it to me?

**Comment by anna-geller** [comment]
sure, you would need to fork the blueprints repo and make a PR for this file https://github.com/kestra-io/blueprints/blob/main/flows/aws-lambda.yaml

**Comment by anna-geller** [comment]
I will close this issue as the blueprint it refers to no longer exists and the blueprint I referenced doesn't need fixing. Sorry for the confusion @rishi-jat  -- perhaps you can contribute your work as a new blueprint in the blueprints repo? Here is a revised version you can contribute:

```yaml
id: aws-lambda
namespace: company.team

tasks:
  - id: sls_commands
    type: io.kestra.plugin.scripts.node.Commands
    taskRunner: 
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: node:18
    env:
      AWS_ACCESS_KEY_ID: "{{ secret('AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
      AWS_DEFAULT_REGION: eu-central-1
    inputFiles:
      serverless.yml: |
        service: lambda
        frameworkVersion: '3'

        provider:
          name: aws
          runtime: python3.9
          region: eu-central-1
          memorySize: 512
          timeout: 10

        functions:
          etl:
            handler: handler.run

      handler.py: |
        import platform
        import sys

        def extract() -> int:
            print("Extracting data...")
            return 21

        def transform(x: int) -> int:
            print("Transforming data...")
            return x * 2

        def load(x: int) -> None:
            print(f"Loading {x} into destination...")

        def run(event=None, context=None):
            raw_data = extract()
            transformed = transform(raw_data)
            load(transformed)
            print("Hello from Kestra 🚀")
            print(f"Host's network name = {platform.node()}")
            print(f"Python version = {platform.python_version()}")
            print(f"Platform information (instance type) = {platform.platform()}")
            print(f"OS/Arch = {sys.platform}/{platform.machine()}")
    commands:
      - npm install -g serverless
      - sls deploy
      - sls invoke -f etl --log
      # - sls remove

extend:
  title: "Deploy new AWS Lambda functions with a serverless framework"
  description: |
    This blueprint demonstrates how to use the Serverless Framework to deploy an
    AWS Lambda function. It includes:

    - A minimal `serverless.yml` configuration file
    - A sample `handler.py` Python file with `extract`, `transform`, and `load`
    functions
    - Commands to install Serverless, deploy the service, and invoke the function

    The blueprint is designed to run in Docker using the `node:18` image. It sets
    up the necessary environment to use Serverless Framework and AWS Lambda
    seamlessly.

    To use this blueprint:

    1. Ensure you have the necessary AWS permissions and your credentials are
    configured.
    2. Adjust the `serverless.yml` and `handler.py` files as needed for your
    application.
    3. Run the blueprint to deploy your Lambda function.
  tags:
    - AWS
    - CLI
  ee: false
  demo: false
  meta_description: This blueprint demonstrates how to use Serverless Framework
    to deploy an AWS Lambda function. It includes a minimal `serverless.yml`
    configuration file, a sample `handler.py` Python file, and commands to
    install Serverless, deploy the service, and invoke the function.
```
