### ISSUE TITLE
Powershell process outputFiles not detecting files after updating to 0.18.2 from 0.17.

### ISSUE THREAD

**Issue by adam133** [kestra-io/plugin-scripts#170]
### Expected Behavior

Thread from Slack: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1724185082477709

0.17 version of flow:
```
  - id: "run_query"
    type: "io.kestra.plugin.scripts.powershell.Commands"
    failFast: false
    runner: PROCESS
    interpreter: [powershell]
    commands: 
      - "<< a powershell command that generates *.tab files in the ./ directory>>"
    outputFiles:
    - "*.tab"
```

0.18.2:
```
  - id: "run_query"
    type: "io.kestra.plugin.scripts.powershell.Commands"
    failFast: false
    taskRunner: 
      type: io.kestra.plugin.core.runner.Process
    interpreter: [powershell]
    targetOS: WINDOWS
    namespaceFiles: 
      enabled: false
    commands: 
      - "<< a powershell command that generates *.tab files in the ./ directory>>"
    outputFiles:
    - "*.tab"
```

outputFiles should be detected same as 0.17

### Actual Behaviour

Task doesn't capture outputs it used to capture:
```
2024-08-20 16:11:17.539 Captured 0 output(s).
```

### Environment Information

- Kestra Version: 0.18.2
Batch script from: https://github.com/kestra-io/kestra/releases/download/v0.18.2/kestra-0.18.2
- Plugin version: LATEST (reinstalled with update)
- Operating System (OS / Docker / Kubernetes): Windows Server 2022 Datacenter
- Java Version (If not docker): From here:
https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/21.0.3+9/openlogic-openjdk-jre-21.0.3+9-windows-x64.zip
