### ISSUE TITLE
Python error logs are captured as WARNING log level

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#190]
### Describe the issue

Repro:

```yaml
id: error_logs_demo
namespace: company.team

tasks:    
  - id: fail
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      raise ValueError("An error occurred: This is a manually raised exception.")
errors:
  - id: alert
    type: io.kestra.plugin.core.log.Log
    message: list of error logs — {{ errorLogs() }}
```

Another example:

```yaml
id: error_logs_demo
namespace: company.team

tasks:    
  - id: fail
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      def divide_numbers(a, b):
          return a / b

      result = divide_numbers(5, 0)
      print(result)

errors:
  - id: alert
    type: io.kestra.plugin.core.log.Log
    message: list of error logs — {{ errorLogs() }}
```

### Environment

- Kestra Version: develop
