### ISSUE TITLE
Kestra task output method - Python boolean not rendered properly

### ISSUE THREAD

**Issue by pdondin** [kestra-io/plugin-scripts#191]
### Describe the issue

Came from this #help message : https://kestra-io.slack.com/archives/C03FQKXRK3K/p1733159976009429

**Context**
I have a python script task that basically ends with : 
```
results = {
    'domain': domain,
    'keywords': keywords,
    'description': description,
    'scraping_successful': scraped_data is not None,
    'scraped_content': scraped_data
}

logger.info(results)
# output data for the next task

Kestra.outputs(results)
```

And while trying to access `{{outputs.scrape_website.vars.results}}`, it ended up as `NameError: name 'true' is not defined. Did you mean: 'True'` 

Discussion with @Ben8t ; it looks like it should have been the case.
PS : More code context in the slack thread if needed

**I found a quick patch going through a json string instead to pass those parameters.**

```
Kestra.outputs({"results": json.dumps(results)})
```

And getting the var using : 
```
input = {{ outputs.scrape_website["vars"] }}
data = json.loads(input['results'])
logger.info(data)
```

### Environment

- Kestra Version: latest
- TaskRunner : Process

**Comment by Pradumnasaraf** [comment]
Now working as expected!

```yaml
id: issue191_pyscript_bool
namespace: qa.issue191


tasks:
  - id: produce
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    beforeCommands:
      - pip install --quiet kestra
    script: |
      from kestra import Kestra
      results = {
          "domain": "example.com",
          "scraping_successful": True,
          "failed": False,
          "scraped_content": None,
      }
      Kestra.outputs(results)

  - id: consume_pebble
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    script: |
      flag = {{ outputs.produce.vars.scraping_successful }}
      failed = {{ outputs.produce.vars.failed }}
      print(f"flag={flag} ({type(flag).__name__})")
      print(f"failed={failed} ({type(failed).__name__})")
      assert flag is True and failed is False
      print("CONSUME_PEBBLE_OK")

  - id: prelude_check
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    script: |
      import json
      t = true
      f = false
      n = null
      print("PRELUDE_OK " + json.dumps({"t": t, "f": f, "n": n}))
      assert t is True and f is False and n is None

```

cc @pdondin
