### ISSUE TITLE
Node.js default example fails due to dependency errors despite running in a default Docker image

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#192]
### Describe the issue

```yaml
id: outputs_nodejs
namespace: company.team

description: This flow will install the npm package in a Docker container, and use kestra's NodeJS Commands task to run the script.

tasks:
  - id: run_nodejs_commands
    type: io.kestra.plugin.scripts.node.Commands
    inputFiles:
      output_nodejs.js: |
        const requestify = require('requestify');
        const Kestra = require('@kestra-io/libs');

        function GetDockerImageDownloads(imageName){
          // Queries the Docker Hub API to get the number of downloads for a specific Docker image.
          var url = `https://hub.docker.com/v2/repositories/${imageName}/`
          console.log(url)
          requestify.get(url)
            .then(function(response) {
              result = JSON.parse(response.body);
              Kestra.outputs({"pull_count": result['pull_count']})
              return result['pull_count'];
            })
            .catch(function(error) {
              console.log(error);
            })
        }

        GetDockerImageDownloads("kestra/kestra")      
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: node:slim
    warningOnStdErr: false
    beforeCommands:
      - npm install requestify
      - npm install @kestra-io/libs
    commands:
      - node outputs_nodejs.js

  - id: log_downloads
    type: io.kestra.plugin.core.log.Log
    message: "Number of downloads: {{ outputs.run_nodejs_commands.vars.pull_count }}"
```

From https://kestra.io/docs/how-to-guides/javascript#variable-output

### Environment

- Kestra Version: develop
