### ISSUE TITLE
Output variables which return None as value are not captured at all

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#195]
### Describe the issue

![image](https://github.com/user-attachments/assets/25915d2c-1788-4e57-90bf-670c307b9d63)

```yaml
id: repro
namespace: company.team

tasks:
  - id: return_null
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      from kestra import Kestra
      Kestra.outputs({'status': None, 'status2': 'hello'})
```

the status should also be captured, just with value `null`

### Environment

- Kestra Version: latest 0.20.6 + develop
