### ISSUE TITLE
Python INFO logs are captured as WARNING log level

### ISSUE THREAD

**Issue by andrei-micuda** [kestra-io/plugin-scripts#200]
### Describe the issue

Sample workflow:
```yaml
id: python_logs_demo
namespace: company.team

tasks:    
  - id: fail
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      import logging
      logging.basicConfig(
        format='%(asctime)s %(levelname)s:%(message)s',
        level=logging.INFO,
        handlers=[
            logging.StreamHandler()])
      logging.info("Tesing...")
```

Expected behaviour:
Logs should be captured with INFO level.

Actual behaviour:
![image](https://github.com/user-attachments/assets/495800b8-0be7-432b-9c69-29df38423fa9)

### Environment

- Kestra Version: v0.20.11
