### ISSUE TITLE
Script tasks emit a lot of warnings — fix dynamic properties in script tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#211]
### Describe the issue

![image](https://github.com/user-attachments/assets/4496d145-c03a-45cc-8f7d-16c6819f8a5b)

![image](https://github.com/user-attachments/assets/fc4634ef-eb43-4bf6-9760-c245b5d47d51)

repro from Brian:
```yaml
id: for-each-item
namespace: io.kestra.bmu

tasks:
  - id: hey
    type: io.kestra.plugin.scripts.shell.Script
    outputFiles:
      - "hello.txt"
    script: |
      echo -e "a\nb\nc" > hello.txt
  - id: hello
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{outputs.hey.outputFiles['hello.txt']}}"
    inputs:
      text: "{{taskrun.items}}"
    namespace: io.kestra.bmu
    flowId: subflow-item
  - id: hi
    type: io.kestra.plugin.core.log.Log
    message: "Hello after"
```

![image](https://github.com/user-attachments/assets/83d7e458-3e74-4f22-9e8c-b7e57dffc9e0)

### Environment

- Kestra Version: develop
