### ISSUE TITLE
Node logs aren't catch properly

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-scripts#216]
### Describe the issue

```yaml
id: node-custom-package
namespace: sanitychecks.flows.blueprints
tasks:
  - id: script
    type: io.kestra.plugin.scripts.node.Script
    inputFiles:
      package.json: |
        {
          "name": "your_project_name",
          "version": "1.0.0",
          "type": "module",
          "dependencies": {
            "colors": "^1.4.0"
          }
        }
    beforeCommands:
      - npm install
    script: |
      import colors from 'colors';
      console.log(colors.red("Hello"));
```

![image](https://github.com/user-attachments/assets/0705950d-bf73-435e-860f-ef4d0ffecc56)

You can see that exit 0 but some errors are caught, should warning I think in this case.

### Environment

- Kestra Version: develop

**Comment by DeepakMaitry** [comment]
May I know the issue and contribute to it, please?

**Comment by Ben8t** [comment]
@DeepakMaitry the issue is already assigned to @mgabelle as he worked on a similar issue recently. You can still look at other open issues with [good first issue tag](https://github.com/kestra-io/kestra/issues?q=is:open+is:issue+label:%22good+first+issue%22) if you're willing to contribute to Kestra.

**Comment by DeepakMaitry** [comment]
Got it, thanks for letting me know! I’ll check out the open issues with the good first issue tag.

**Comment by Ben8t** [comment]
Closing in favor of adding a custom Node logger through the Kestra lib: https://github.com/kestra-io/libs/issues/22

For now, using warningOnStdErr property allows to make the flow to pass in WARNING state

```yaml
id: node-custom-packageg
namespace: sanitychecks.flows.blueprints
tasks:
  - id: script
    type: io.kestra.plugin.scripts.node.Script
    warningOnStdErr: true
    inputFiles:
      package.json: |
        {
          "name": "your_project_name",
          "version": "1.0.0",
          "type": "module",
          "dependencies": {
            "colors": "^1.4.0"
          }
        }
    beforeCommands:
      - npm install
    script: |
      import colors from 'colors';
      console.log(colors.red("Hello"));
```
