### ISSUE TITLE
GitSyncFlows with childNamespace surcharge too much

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-scripts#223]
### Describe the issue

https://jam.dev/c/08152870-16ee-40e0-ae2f-5a176e48de58

Using this flow:

```
id: test_git_sync
namespace: sanitychecks

tasks:
  - id: git_sync
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/kestra-io/blueprints
    gitDirectory: sanitychecks
    targetNamespace: integration
    includeChildNamespaces: true
```

All the children flow imported thanks to `includeChildNamespaces: true` are not using fully the `targetNamespace: integration` but something like `integration.<folder_name>.<subfolder_name>`

`targetNamespace: integration` is yet explicit and should put the corresponding namespace to children flows

### Environment

- Kestra Version: develop
