### ISSUE TITLE
Add support for AWS ECR

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#48]
### Feature description

Usually, when working with private Docker registries in Script tasks, you can do:

```yml
id: pythonCommandsExample
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/examples
        branch: main

      - id: gitPythonScripts
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        runner: DOCKER
        docker:
          image: ghcr.io/kestra-io/pydata:latest
          config: |
            {
              "auths": {
                  "https://index.docker.io/v1/": {
                      "username": "annageller",
                      "password": "dckr_pat_xxxxx"
                  }
              }
            }
        beforeCommands:
          - pip install faker > /dev/null
        commands:
          - python scripts/etl_script.py
          - python scripts/generate_orders.py
      
      - id: outputFile
        type: io.kestra.core.tasks.storages.LocalFiles
        outputs:
          - orders.csv

  - id: loadCsvToS3
    type: io.kestra.plugin.aws.s3.Upload
    accessKeyId: "{{secret('AWS_ACCESS_KEY_ID')}}"
    secretKeyId: "{{secret('AWS_SECRET_ACCESS_KEY')}}"
    region: eu-central-1
    bucket: kestraio
    key: stage/orders.csv
    from: "{{outputs.outputFile.uris['orders.csv']}}"
```

However, this doesn't work with ECR as it requires a token retrieved using `aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 338306982838.dkr.eu-central-1.amazonaws.com`

TBD: figure out a simple solution, optionally combining it with https://github.com/kestra-io/plugin-aws/pull/199

**Comment by anna-geller** [comment]
With the addition of the AwsCLI task, this is now possible! 🎉

See the usage example in the following blueprint: https://demo.kestra.io/ui/blueprints/community/101 

copy:

```yaml
id: awsECR
namespace: dev

tasks:
  - id: aws
    type: io.kestra.plugin.aws.cli.AwsCLI
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: eu-central-1
    commands:
      - TOKEN=$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 --decode | cut -d':' -f2)
      - echo "::{\"outputs\":{\"token\":\"$TOKEN\"}}::"

  - id: py
    type: io.kestra.plugin.scripts.python.Commands
    docker:
      image: 338306982838.dkr.ecr.eu-central-1.amazonaws.com/data-infastructure:latest
      config: |
        {
          "auths": {
            "338306982838.dkr.ecr.eu-central-1.amazonaws.com": {
                "username": "AWS",
                "password": "{{outputs.aws.vars.token}}"
              }
          }
        }
    commands:
      - python --version # e.g. python yourscript.py

```
