### ISSUE TITLE
The `taskDefaults` doesn't apply to script tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#49]
### Expected Behavior

Using this reproducer, you'll notice that the explicitly defined image (`ghcr.io/kestra-io/pydata:latest`) in the first Script task applies (as expected), but the next task is expected to use the default image provided in `taskDefaults` but it doesn't -- it directly uses the `python:latest` image instead of trying to first check if there are any `taskDefaults` for that task type.

```yaml
id: pandasETLnew
namespace: blueprint

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: extractCsv
        type: io.kestra.plugin.scripts.python.Script
        script: |
          import pandas as pd
          data = {
              'Column1': ['A', 'B', 'C', 'D'],
              'Column2': [1, 2, 3, 4],
              'Column3': [5, 6, 7, 8]
          }
          df = pd.DataFrame(data)
          df.to_csv("data.csv", index=False)
        warningOnStdErr: false
        docker:
          image: ghcr.io/kestra-io/pydata:latest

      - id: outputFiles
        type: io.kestra.core.tasks.storages.LocalFiles
        outputs:
          - "*.csv"

      - id: inputFiles
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          data.csv: "{{outputs.outputFiles.uris['data.csv']}}"

      - id: transformAndLoadCsv
        type: io.kestra.plugin.scripts.python.Script
        script: |
          import pandas as pd
          df = pd.read_csv("data.csv")
          df['Column4'] = df['Column2'] + df['Column3']
          df.to_csv("final_result.csv", index=False)

taskDefaults:
  - type: io.kestra.plugin.scripts.python.Script
    values:
      warningOnStdErr: false
      docker:
        image: ghcr.io/kestra-io/pydata:latest
```

### Actual Behaviour

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/9a5cc93a-cb42-4002-a98c-da732bbfff57)

### Environment Information

- Kestra Version: develop-full 0.10.1
