### ISSUE TITLE
Allow users to set Workdir of the docker container

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-scripts#76]
### Feature description

Currently it's not possible to set the `--workdir` param of the container (which sould be relative to the current workdir of the container).

Having this option make some Docker images way easier to use like [Terraform](https://hub.docker.com/r/hashicorp/terraform/) image.

In order to perform `terraform plan` in the correct location within our Kestra `WorkingDirectory`, we need to be able to specify this option to tell the container where is our terraform code (i.e. `/environment/dev`) in the mounted volume

**Comment by anna-geller** [comment]
Did changing the entrypoint work? I see your point and wonder what's the least intrusive way of tackling it

Absolute path to a script from a container seems most declarative and explicit

**Comment by aballiet** [comment]
> Did changing the entrypoint work? I see your point and wonder what's the least intrusive way of tackling it
> 
> Absolute path to a script from a container seems most declarative and explicit

Yes but then need to provide the entrypoint of the image which is kind of confusing for an user. See example below with Terraform : 

```YAML
    docker:
      image: hashicorp/terraform:latest
      entryPoint:
      - ""
      pullPolicy: IF_NOT_PRESENT
    commands:
    - cd environment/development
    - /bin/terraform init -var-file=ci_cd.tfvars
    - /bin/terraform plan -var-file=ci_cd.tfvars
```

IMO `/bin/terraform` is not super easy to find if you are a beginner.
<img width="1268" alt="image" src="https://github.com/kestra-io/plugin-scripts/assets/25565600/b5760bba-9028-412c-885e-4f2f166d6c9f">

Leveraging `--workdir` is more straightforward for me in that case. Having `entryPoint: [""]` feels hacky
